<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameHours.Core\GameHours.Core.csproj" />
    <ProjectReference Include="..\GameHours.Storage\GameHours.Storage.csproj" />
    <ProjectReference Include="..\GameHours.Windows\GameHours.Windows.csproj" />
    <ProjectReference Include="..\GameHours.Sync\GameHours.Sync.csproj" />
    <ProjectReference Include="..\GameHours.Update\GameHours.Update.csproj" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
</Project>
