<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GameHours.Core\GameHours.Core.csproj" />
    <PackageReference Include="Microsoft.Database.ManagedEsent" />
  </ItemGroup>
</Project>
